services:
  flask-app:
    build: .
    container_name: flask-app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    ports:
      - "${REST_PORT}:${REST_PORT}"
      - "${WEB_PORT}:${WEB_PORT}"

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: users
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  db_init:
    build:
      context: .
    environment:
      - DATABASE_HOST=db
    command: "python create_table.py"