name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: adminadmin
          MYSQL_DATABASE: users
        options: >-
          --health-cmd="mysqladmin ping -uroot -padminadmin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create Docker network
      run: |
        docker network create userregistry_mynet || true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker containers
      run: |
        docker-compose down -v || true
        docker-compose build
        docker-compose up -d

    - name: Wait for services to be up
      run: |
        # Wait for MySQL and Flask services to be up
        docker-compose run db-init bash -c "while ! nc -z db 3306; do sleep 1; done"

    - name: Post a new user using curl
      run: |
        # Wait until the Flask app is up and running
        sleep 10
        curl -X POST -H "Content-Type: application/json" \
          -d '{"user_name": "testuser", "creation_date": "2024-09-26"}' \
          http://127.0.0.1:5000/users

    - name: Run combined tests
      run: |
        python tests/combined_testing.py

    - name: Clean up Docker containers
      if: always()
      run: |
        docker-compose down -v
