name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 0:3306
        env:
          MYSQL_ROOT_PASSWORD: adminadmin
          MYSQL_DATABASE: users
        options: >-
          --health-cmd="mysqladmin ping -uroot -padminadmin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker containers
      run: |
        docker-compose down -v || true
        docker-compose build
        docker-compose up -d

    - name: Wait for services to be up
      run: |
        docker-compose run db-init bash -c "while ! nc -z db 3306; do sleep 1; done"

    - name: Check MySQL Logs
      run: |
        docker-compose logs db

    - name: Run combined tests
      env:
        DATABASE_HOST: db
        DATABASE_PORT: 3306
        DATABASE_USER: root
        DATABASE_PASSWORD: adminadmin
      run: |
        python tests/combined_testing.py

    - name: Clean up Docker containers
      if: always()
      run: |
        docker-compose down -v